apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../../base/platform/external-dns
  - sa.yaml
  - secret-azure.yaml  

# Patch StrategicMerge (obligatoire) pour surcharger le HelmRelease
patchesStrategicMerge:
  - values-staging.yaml

# Générer le Secret à partir du fichier azure.json du repo
#secretGenerator:
#  - name: external-dns-azure
#    files:
 #     - azure.json=./secrets/azure.json

generatorOptions:
  disableNameSuffixHash: true

namespace: external-dns
