apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/platform/external-dns
  - sa.yaml                           # ⬅️ ajoute le SA
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: external-dns
      namespace: external-dns
