apiVersion: v1
kind: Secret
metadata:
  name: external-dns-azure
  namespace: external-dns
type: Opaque
stringData:
  azure.json: |-
    {
      "tenantId": "9ffc6712-5ed6-4651-9b81-51f454114654",
      "subscriptionId": "ec0e829d-64e1-43fd-b721-ecf5b5112773",
      "resourceGroup": "ihsen",
      "useWorkloadIdentityExtension": true
      /* Optionnel : "aadClientId": "<CLIENT_ID_UAMI>" */
    }
