apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  values:
    # Identifiant TXT unique par cluster pour éviter les conflits
    txtOwnerId: "aks-staging-01"

    # IMPORTANT: label sur le Pod (depuis WI >= 1.0.0, le label doit être sur le Pod)
    podLabels:
      azure.workload.identity/use: "true"

    # Monte le Secret contenant /etc/kubernetes/azure.json
    extraVolumes:
      - name: azure-config-file
        secret:
          secretName: external-dns-azure
    extraVolumeMounts:
      - name: azure-config-file
        mountPath: /etc/kubernetes
        readOnly: true

    # Provider ExternalDNS (nouvelle convention du chart)
    provider:
      name: azure
    sources:
      - ingress

    # Conserve quelques flags utiles
    registry: txt
    policy: sync

    # (Optionnel) Si tu veux filtrer un domaine :
    # extraArgs:
    #   - --domain-filter=example.com

    # (Optionnel) Si tu utilises Azure Private DNS :
    # extraArgs:
    #   - --azure-use-private-dns
