apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: "kvp-demo-001.privatelink.vaultcore.azure.net"
      tenantId: "9ffc6712-5ed6-4651-9b81-51f454114654"
      authType: WorkloadIdentity
      # 👉 très important : on lie ce Store au SA du contrôleur (celui qui porte la WI)
      serviceAccountRef:
        name: external-secrets
        namespace: external-secrets

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
name: azure-keyvault
spec:
provider:
azurekv:
authType: WorkloadIdentity
vaultUrl: https://<KEYVAULT_NAME>.vault.azure.net
# Option A (recommended): use the referenced service account
serviceAccountRef:
name: es-azure-wi
namespace: external-secrets
# Optionally also set tenantId directly if you prefer not to annotate the SA
# tenantId: <AZURE_TENANT_ID>