# base/platform/external-secrets/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  chart:
    spec:
      chart: external-secrets
      # version: ">=0.9.0"   # ta contrainte si tu en as une
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  values:
    installCRDs: true           # ⬅️ IMPORTANT
    serviceAccount:
      create: false
      name: external-secrets
