apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 10m
  chart:
    spec:
      chart: external-dns
      version: ">=1.15.0"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    sources: ["ingress"]
    provider: azure
    registry: txt
    policy: sync
    serviceAccount:
      create: false         # ⬅️ change
      name: external-dns    # ⬅️ use SA créé en overlay
    extraArgs:
      - --interval=1m
      - --log-format=json
