apiVersion: helm.toolkit.fluxcd.io/v2 
kind: HelmRelease 
metadata: 
  name: traefik 
  namespace: platform 
spec: 
  valuesFrom: 
    - kind: ConfigMap 
      name: traefik-values 
      valuesKey: values.yaml 
