apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-staging-stores
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets-staging   # ⬅️ attend que le contrôleur (et ses CRDs) soit prêt
  interval: 5m
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./clusters/staging/platform/external-secrets/stores
