apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  path: ./clusters/staging/platform/external-secrets/stores
  dependsOn:
    - name: external-secrets
  healthChecks:
    - apiVersion: external-secrets.io/v1beta1
      kind: ClusterSecretStore
      name: azure-keyvault
  timeout: 5m