apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  path: ./base/platform/external-secrets
  dependsOn:
    - name: helm-repositories
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
  targetNamespace: external-secrets
  timeout: 5m