apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 3m
  path: ./base/flux/helmrepositories