apiVersion: kustomize.config.k8s.io/v1beta1 
kind: Kustomization 
resources: 
  - ../../namespaces/monitoring.yaml 
  - ../../flux/helmrepositories/prometheus-community.yaml 
  - helmrelease.yaml 