apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: "kvp-demo-001.privatelink.vaultcore.azure.net"
      tenantId: "9ffc6712-5ed6-4651-9b81-51f454114654"
      authType: WorkloadIdentity
      serviceAccountRef:              # ⬅️ important
        name: external-secrets
        namespace: external-secrets
