apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: "https://<YOUR_KV_NAME>.vault.azure.net/"
      tenantId: "<TENANT_ID>"
      authType: WorkloadIdentity
      serviceAccountRef:              # ⬅️ important
        name: external-secrets
        namespace: external-secrets
