apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: https://<KEYVAULT_NAME>.vault.azure.net
      # Option A (recommended): use the referenced service account
      serviceAccountRef:
        name: es-azure-wi
        namespace: external-secrets
      # Optionally also set tenantId directly if you prefer not to annotate the SA
      # tenantId: <AZURE_TENANT_ID>