apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../../base/platform/external-secrets
  - sa.yaml                                  # ⬅️ ajoute le SA
  - clustersecretstore-azure.yaml
patches:
  - path: values-staging.yaml
    target:
      kind: HelmRelease
      name: external-secrets
      namespace: external-secrets
