/*
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets
  namespace: external-secrets
  annotations:
    azure.workload.identity/client-id: "<ESO_APP_CLIENT_ID>"
  labels:
    azure.workload.identity/use: "true"
*/
---
apiVersion: v1
kind: ServiceAccount
metadata:
  # this service account was created by azwi
  name: workload-identity-sa
  annotations:
    azure.workload.identity/client-id: 02b0b56c-99cc-4491-9f18-288b76702508
    azure.workload.identity/tenant-id: 9ffc6712-5ed6-4651-9b81-51f454114654
---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: example-secret-store
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://kvp-demo-001.vault.azure.net/"
      # note: no serviceAccountRef was provided