apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: "02b0b56c-99cc-4491-9f18-288b76702508"  # App reg (federated) pour ESO controller
