apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    serviceAccount:
      annotations:
        azure.workload.identity/client-id: ""  # App reg (federated) pour ESO controller
