apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  values:
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      create: false
      name: external-secrets

