apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kustomizations/helm-repositories.yaml     # ← AJOUTE CETTE LIGNE
  - kustomizations/traefik.yaml
  - kustomizations/monitoring.yaml
  - kustomizations/cert-manager.yaml
  - kustomizations/cert-issuers.yaml
  - kustomizations/external-dns.yaml
  - kustomizations/external-secrets.yaml
  - kustomizations/external-secrets-stores.yaml

