apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 10m
  valuesFrom:
    - kind: ConfigMap
      name: kps-values
      valuesKey: values.yaml