apiVersion: helm.toolkit.fluxcd.io/v2 
kind: HelmRelease 
metadata: 
  name: traefik 
  namespace: platform 
spec: 
  interval: 10m 
  chart: 
    spec: 
      chart: traefik 
      version: ">=26.0.0" 
      sourceRef: 
        kind: HelmRepository 
        name: traefik 
        namespace: flux-system 
  install: 
    remediation: 
      retries: 3 
  upgrade: 
    remediation: 
      retries: 3 
  values:
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
    service:
      type: LoadBalancer
      # --- Option IP publique statique Azure (décommente si tu as une Public IP existante) ---
      # annotations:
      #   service.beta.kubernetes.io/azure-load-balancer-resource-group: "<RG-de-la-PublicIP>"
      # loadBalancerIP: "<IP_publique_Statique>"
      # ----------------------------------------------------------------------------------------
      spec:
        externalTrafficPolicy: Local
    logs:
      access:
        enabled: true
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true